### ISSUE TITLE
ARK Glossary

### ISSUE THREAD

**Issue by kristjank** [ArkEcosystem/docs#28]
Collect the most used terms and their explanations in short meaningful sentences with additional explanation and possible links to other resources. This topic should follow the basic glossary guidelines, e.g. by using term and delivering its short definition or explanation.

Some terms that would fit nicely into Glossary
--
What is an "Account"?
What is a "Block"?
What is a "Delegate"?
What is a "Loader"?
What is a "Peer"?
What is a "Node"?
What is a "Signature"?
What is a "MultiSignature"?
What is a "Transaction"?
What is a "Transport"?
What is a "Dark Adress"?
What is a "Reward"?
What is a "Fee"?
What is a "Height"?
What is a "Forged"?
What is a "Block missed"?
What is an "Approval"?
What is a "Vote"?
What is a "Voter"?

---

**Comment by VonHazze25** [comment]
Trying to contribute. Learning how Github works. Want to attempt the Ark glossary. Initially for bounty now just for pride.
