### ISSUE TITLE
What is an address and how is it generated

### ISSUE THREAD

**Issue by kristjank** [ArkEcosystem/docs#4]
Explain to the reader the concept of address in blockchain world. Use some examples and relate it to the real-work (e.g. bank account owned by only you). 
Include topics:
- address and its relation to passphrase
- passphrase relation to Public And Private Keys
- the importance of securely storing the passphrase (ledger, paper, bank safe) 

Please follow the contributing guidelines and general structure as defined in README.md

**Comment by Moustikitos** [comment]
Hi, i can go for this subject.

**Comment by Moustikitos** [comment]
hey... i think mermaid is something to be installed.
https://github.com/knsv/mermaid
![mermaid-glimpse](https://user-images.githubusercontent.com/15268977/38457216-c16f1224-3a8d-11e8-9ada-ed0a51a0424b.jpg)
